config/routes.rb
Rails.application.routes.draw do
  resources :homes 

   root 'homes#index'

      get 'about_us'  ,   :controller => 'homes' , :action => 'about_us'
   

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

 def about_us
    
  end
  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
          gflash :success => "Thanks for contact us. We connect shortly.!"
         format.html { redirect_to root_url }
     #   format.html { redirect_to root_url, notice: 'Thanks fot contact us. We connect shortly.' }
      #  format.json { render :index, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
       params.require(:home).permit(:name , :email ,:phone ,:sbject , :query )
     
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :sbject %><br>
    <%= f.text_field :sbject %>
  </p>
  <p>
    <%= f.label :query %><br>
    <%= f.text_area :query %>
  </p>
  <div class="actions">
    <%= f.submit "SUBMIT" %>
  </div>
<% end %>

app/views/homes/about_us.html.erb
<p>AADHAR ACADEMY FOR ALL COMPETITIONS is the premier institute with unmatched leadership in one day competition preparation. It is known for high standard of teaching since its inception in 2012. We delivered excellence in teaching and had made the institute a path setter in HARYANA.

We are a team of enthusiastic, dedicated and hardworking people with ultimate aim to sharpen the skill and shape the career of aspirants, preparing for one day competitions. We believe in team efforts and work for the holistic development of students at each level. We educate students to make them more efficient and goal oriented by our interactive classroom programme. We provide great learning environment where all students are practiced in order to compete for the best result.</p>
ALL THE BEST

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<!--<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each# do |home| %>
      <tr>
        <td><%#= link_to 'Show', home %></td>
        <td><%#= link_to 'Edit', edit_home_path(home) %></td>
        <td><%#= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Home', new_home_path %>-->


<h1>Our Institute</h1>

AADHAR ACADEMY  FOR ALL COMPETITIONS is the premier institute with unmatched leadership in one day competition preparation. It is known for high standard of teaching since its inception in 2012. We delivered excellence in teaching and had made the institute a path setter in HARYANA.

We are a team of enthusiastic, dedicated and hardworking people with ultimate aim to sharpen the skill and shape the career of aspirants, preparing for one day competitions. We believe in team efforts and work for the holistic development of students at each level. We educate students to make them more efficient and goal oriented by our interactive.





<h1>Motivation and Inspirations Tips.....</h1>
<h2>Education is the most powerful weapon which you can use to change the world.<p>Nelson Mandela</p> </h2>
<h2>The roots of education are bitter, but the fruit is sweet.<p>Aristotle</p></h2>

<h2>An investment in knowledge pays the best interest.<p>Benjamin Franklin</p></h2>


<h2>Education is not preparation for life; education is life itself.<p>John Dewey</p></h2>


<h2>Good, better, best. Never let it rest. 'Til your good is better and your better is best.<p>St. Jerome</p></h2>

<h2>The way to get started is to quit talking and begin doing.<p>Walt Disney</p></h2>

<h2>In order to succeed, we must first believe that we can.<p>Nikos Kazantzakis</p></h2>

<h2>You are never too old to set another goal or to dream a new dream.<p>C. S. Lewis</p></h2>

app/views/homes/new.html.erb
<!-- <div class="heading">
</div>

 -->
<h1>Contact us</h1>
<%= render 'form' %>

<%#= link_to 'Back', homes_path %>



<!-- <div class="footer">
  <div class="row">
    <div class="small-12 columns">
      <pre>Aadhar Academy  provide right direction for  future.
      </pre>
    </div>
  </div>
</div> -->

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AadharDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= gflash %>
  <%= render 'shared/header' %>
<%= yield %>
<%= render 'shared/footer' %>

</body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="row">
    <div class="small-12 columns">
      <pre>Aadhar Academy  provide right direction for  future.
      </pre>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="title-area">
   <div class="navbar-class">
      <div class="container">
<!--         <ul class="nav navbar-nav">
 -->    <div class="logo_tab">     
 <%= link_to image_tag('aafinal.png'), 'http://localhost:3000/'%><%= link_to image_tag('aa2.png')   %>
<!--         <div class="tab">
 -->          <div class="inner"><%= button_to "HOME", root_path, :method => "get" ,  :class =>"dropbtn"%></div>
          <div class="inner"><%= button_to "ABOUT US", about_us_path, :method => "get" ,  :class =>"dropbtn"%></div>
          <div class="inner"><div class="dropdown">

            <button class="dropbtn">COURSES</button>
            <div class="dropdown-content">
              <a href="#">SSC</a>
              <a href="#">BANKING</a>
              <a href="#">POLICE</a>
              <a href="#">DEFENCE</a>
            </div>
          </div></div>
         <div class="inner"> <%= button_to "CONTACT", new_home_path, 
          :method => "get" , :class =>"dropbtn"%></div> 
<!--           </div> 
 -->          </div>   
 <!--         </ul>
 -->      

      </div>
    </div>

      
      